<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-OKDV62E" ignored="0" name="Test(failed)" tests="7" failures="7" timestamp="2020-02-26T11:48:03 EST" time="11.839" errors="0">
  <testcase name="testMethod4" time="5.614" classname="testng.testingonly">
    <failure type="java.lang.AssertionError" message="Failed at Login did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at Login did not expect to find [true] but found [false]
at testng.testingonly.doWork(testingonly.java:448)
at testng.testingonly.testMethod4(testingonly.java:443)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMethod4 -->
  <testcase name="testMethod3" time="5.613" classname="testng.testingonly">
    <failure type="java.lang.AssertionError" message="Failed at Login did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at Login did not expect to find [true] but found [false]
at testng.testingonly.doWork(testingonly.java:448)
at testng.testingonly.testMethod3(testingonly.java:393)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase name="testMethod" time="5.613" classname="testng.testingonly">
    <failure type="java.lang.AssertionError" message="Failed at Login did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at Login did not expect to find [true] but found [false]
at testng.testingonly.doWork(testingonly.java:448)
at testng.testingonly.testMethod(testingonly.java:298)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMethod -->
  <testcase name="testMethod2" time="5.618" classname="testng.testingonly">
    <failure type="java.lang.AssertionError" message="Failed at Login did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at Login did not expect to find [true] but found [false]
at testng.testingonly.doWork(testingonly.java:448)
at testng.testingonly.testMethod2(testingonly.java:347)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod2" time="5.833" classname="testng.testingonly">
    <failure type="java.lang.AssertionError" message="Failed at Login did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at Login did not expect to find [true] but found [false]
at testng.testingonly.doWork(testingonly.java:448)
at testng.testingonly.testMethod2(testingonly.java:347)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod3" time="5.841" classname="testng.testingonly">
    <failure type="java.lang.AssertionError" message="Failed at Login did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at Login did not expect to find [true] but found [false]
at testng.testingonly.doWork(testingonly.java:448)
at testng.testingonly.testMethod3(testingonly.java:393)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase name="testMethod" time="5.842" classname="testng.testingonly">
    <failure type="java.lang.AssertionError" message="Failed at Login did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed at Login did not expect to find [true] but found [false]
at testng.testingonly.doWork(testingonly.java:448)
at testng.testingonly.testMethod(testingonly.java:298)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- testMethod -->
</testsuite> <!-- Test(failed) -->
