<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="c0016390" failures="17" tests="69" name="eraRerate.eraRerateTestNGSlow" time="5481.840" errors="4" timestamp="2020-12-18T00:48:50 UTC" skipped="23">
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="111.870"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="117.460"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="70.977">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="85.733"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="92.913"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="96.044"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.994">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="30.258"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="71.212">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="67.881">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="149.747"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod4" time="0.000">
    <error message="
Data Provider public synchronized java.lang.Object[][] eraRerate.eraRerateTestNGSlow.dataProviderMethod4() returned a null value" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] eraRerate.eraRerateTestNGSlow.dataProviderMethod4() returned a null value
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:147)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod4 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.586">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="71.475">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="112.290">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="111.964"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="112.106"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.256">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="92.951"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.926">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.249">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="84.224"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="113.532"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.674">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.501">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.117">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="116.018">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.214">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot; /html/body/div[2]/div/div/div/div/div[1]/div[2]/div/div/div/div[2]/div/div/div/div/form/div/div/div[1]/div[5]/div[3]/div/div/div/select&quot;}
  (Session info: chrome=87.0.4280.88)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:25:48&#039;
System info: host: &#039;C0016390&#039;, ip: &#039;10.242.69.100&#039;, os.name: &#039;Windows Server 2016&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;11.0.6&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.41.578737 (49da6702b16031..., userDataDir: C:\Users\5194105\AppData\Lo...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:61404}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 87.0.4280.88, webStorageEnabled: true}
Session ID: fa590aacc71692267309ccd5ac9bc31d
*** Element info: {Using=xpath, value= /html/body/div[2]/div/div/div/div/div[1]/div[2]/div/div/div/div[2]/div/div/div/div/form/div/div/div[1]/div[5]/div[3]/div/div/div/select}" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":" /html/body/div[2]/div/div/div/div/div[1]/div[2]/div/div/div/div[2]/div/div/div/div/form/div/div/div[1]/div[5]/div[3]/div/div/div/select"}
  (Session info: chrome=87.0.4280.88)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'C0016390', ip: '10.242.69.100', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.41.578737 (49da6702b16031..., userDataDir: C:\Users\5194105\AppData\Lo...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:61404}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 87.0.4280.88, webStorageEnabled: true}
Session ID: fa590aacc71692267309ccd5ac9bc31d
*** Element info: {Using=xpath, value= /html/body/div[2]/div/div/div/div/div[1]/div[2]/div/div/div/div[2]/div/div/div/div/form/div/div/div[1]/div[5]/div[3]/div/div/div/select}
at jdk.internal.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1079)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="94.008"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod2" time="0.000">
    <error message="
Data Provider public synchronized java.lang.Object[][] eraRerate.eraRerateTestNGSlow.dataProviderMethod2() returned a null value" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] eraRerate.eraRerateTestNGSlow.dataProviderMethod2() returned a null value
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:147)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod2 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="113.501">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.587">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="100.249"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="113.644">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="16.169"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="110.759"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="118.815">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="83.508"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="85.689"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="111.973">
    <failure message="Failed Selecting Contact Method and Clicking Continue" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed Selecting Contact Method and Clicking Continue
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1227)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod3" time="0.000">
    <error message="
Data Provider public synchronized java.lang.Object[][] eraRerate.eraRerateTestNGSlow.dataProviderMethod3() returned a null value" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] eraRerate.eraRerateTestNGSlow.dataProviderMethod3() returned a null value
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:147)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod3 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="98.535"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="70.173">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="70.260">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.803">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="67.552">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="0.290"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="96.446"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="115.744">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.852">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="115.999"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.501">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.252">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.988">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="113.554"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="115.368">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="73.266">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="70.050">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.644">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="67.807">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.919">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="109.436">
    <failure message="Failed Selecting Contact Method and Clicking Continue" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed Selecting Contact Method and Clicking Continue
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1227)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="73.633">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="0.186"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="70.249">
    <failure message="After Rerate Click No Data Came -- Unknown Error" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Rerate Click No Data Came -- Unknown Error
at org.testng.Assert.fail(Assert.java:99)
at eraRerate.eraRerateTestNGSlow.doEraRerate(eraRerateTestNGSlow.java:1110)
at eraRerate.eraRerateTestNGSlow.testMethod1(eraRerateTestNGSlow.java:542)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="69.538">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="71.455">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="112.434"/>
  <system-out/>
  <testcase classname="eraRerate.eraRerateTestNGSlow" name="testMethod1" time="68.832">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
</testsuite> <!-- eraRerate.eraRerateTestNGSlow -->
