<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="c0016390" failures="17" tests="109" name="rebill.testngRebillFast" time="4068.215" errors="10" timestamp="2020-12-15T22:59:00 UTC" skipped="72">
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.443">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="47.352">
    <failure message="Faled At Last Rebill Screen: Did not reach override errors or failed here" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Faled At Last Rebill Screen: Did not reach override errors or failed here
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1756)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="41.405">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rebill.testngRebillFast.validateResults(testngRebillFast.java:1903)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1686)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="28.064">
    <failure message="Failed at Drop Down" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed at Drop Down
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1239)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.530"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="44.539">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="45.091">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="53.996"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="45.859">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="50.260">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="6.068"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.996">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="45.968">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="40.968">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="45.598">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.277">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.548">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.834">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.639">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rebill.testngRebillFast.validateResults(testngRebillFast.java:1903)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1686)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.576">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="47.108">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="47.871">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="30.540">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="28.729">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="45.894">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rebill.testngRebillFast.validateResults(testngRebillFast.java:1903)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1686)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="45.252">
    <failure message="Could Not go to phone detail screen" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Could Not go to phone detail screen
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1440)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="44.661">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.993">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="41.650">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.910">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.371">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="40.266">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.778">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.015">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rebill.testngRebillFast.validateResults(testngRebillFast.java:1903)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1686)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="39.607">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod4" time="0.000">
    <error message="
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod4() returned a null value" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod4() returned a null value
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:147)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod4 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.081">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="44.004">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="40.443">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="44.336">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="40.351">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.610">
    <failure message="Failed on Entering Tracking Number" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed on Entering Tracking Number
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1030)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.486">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.091">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.872">
    <failure message="Failed on Entering Tracking Number" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed on Entering Tracking Number
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1030)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="28.018">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="43.440">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.306">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.895">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="43.315">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rebill.testngRebillFast.validateResults(testngRebillFast.java:1903)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1686)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.346">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="29.258">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="41.545">
    <failure message="Faled At Last Rebill Screen: Did not reach override errors or failed here" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Faled At Last Rebill Screen: Did not reach override errors or failed here
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1756)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="43.645">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="51.881">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.349">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="44.508">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="44.918"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.464">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rebill.testngRebillFast.validateResults(testngRebillFast.java:1903)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1686)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="44.614">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.082">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="32.250">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="28.741">
    <failure message="Failed at Drop Down" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed at Drop Down
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1239)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.087">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="31.334">
    <failure message="Failed at Drop Down" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed at Drop Down
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1239)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.780">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.386">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="39.965">
    <failure message="Faled At Last Rebill Screen: Did not reach override errors or failed here" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Faled At Last Rebill Screen: Did not reach override errors or failed here
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1756)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="53.614"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="41.238"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="48.432">
    <failure message="Faled At Last Rebill Screen: Did not reach override errors or failed here" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Faled At Last Rebill Screen: Did not reach override errors or failed here
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1756)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.995">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="17.431">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="43.282">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="47.433">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="16.000">
    <failure message="Failed on Entering Tracking Number" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed on Entering Tracking Number
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1030)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.736">
    <failure message="Failed on Entering Tracking Number" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed on Entering Tracking Number
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1030)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.917">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.728">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="44.011">
    <failure message="Faled At Last Rebill Screen: Did not reach override errors or failed here" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Faled At Last Rebill Screen: Did not reach override errors or failed here
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1756)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.048">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="41.483">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="49.937">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="40.685">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.558">
    <failure message="Faled At Last Rebill Screen: Did not reach override errors or failed here" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Faled At Last Rebill Screen: Did not reach override errors or failed here
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1756)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="27.609">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.134">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at rebill.testngRebillFast.validateResults(testngRebillFast.java:1903)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1686)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="41.204">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="54.701"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="48.576">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="43.711">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="50.668">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="29.165">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.481">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="49.606">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="27.002">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.367">
    <failure message="Faled At Last Rebill Screen: Did not reach override errors or failed here" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Faled At Last Rebill Screen: Did not reach override errors or failed here
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1756)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="46.486"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.853">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="28.496">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="54.750"/>
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.562">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="41.294">
    <failure message="Faled At Last Rebill Screen: Did not reach override errors or failed here" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Faled At Last Rebill Screen: Did not reach override errors or failed here
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1756)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="45.744">
    <failure message="Could Not go to phone detail screen" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Could Not go to phone detail screen
at org.testng.Assert.fail(Assert.java:99)
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1440)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod2" time="0.000">
    <error message="
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod2() returned a null value" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod2() returned a null value
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:147)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod2 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.554">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod3" time="0.000">
    <error message="
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod3() returned a null value" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod3() returned a null value
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:147)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- testMethod3 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="40.912">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <system-out/>
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="42.755"/>
  <system-out/>
</testsuite> <!-- rebill.testngRebillFast -->
