<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="c0016390" failures="5" tests="11" name="Rebill Test" time="136.051" errors="0" timestamp="2020-12-17T19:08:36 UTC">
  <testcase classname="rebill.testngRebillFast" name="testMethod4" time="0.0">
    <failure type="org.testng.TestNGException" message="
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod4() returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod4() returned a null value
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testMethod4 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod3" time="0.0">
    <failure type="org.testng.TestNGException" message="
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod3() returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod3() returned a null value
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod2" time="0.0">
    <failure type="org.testng.TestNGException" message="
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod2() returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] rebill.testngRebillFast.dataProviderMethod2() returned a null value
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="14.629">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="16.099">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="16.105">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.987">
    <failure type="java.lang.AssertionError" message="Failed on Entering Tracking Number">
      <![CDATA[java.lang.AssertionError: Failed on Entering Tracking Number
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1030)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="15.888">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="16.081">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="16.469">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase classname="rebill.testngRebillFast" name="testMethod1" time="16.289">
    <failure type="java.lang.AssertionError" message="Failed on Entering Tracking Number">
      <![CDATA[java.lang.AssertionError: Failed on Entering Tracking Number
at rebill.testngRebillFast.doRebill(testngRebillFast.java:1030)
at rebill.testngRebillFast.testMethod1(testngRebillFast.java:634)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
</testsuite> <!-- Rebill Test -->
