<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-OKDV62E" ignored="0" name="Rebill Test" tests="23" failures="8" timestamp="2020-10-06T12:17:41 EDT" time="0.431" errors="0">
  <testcase name="testMethod4" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <failure type="org.testng.TestNGException" message="
Data Provider public synchronized java.lang.Object[][] credit_debit.creditDebitTestNGSlow.dataProviderMethod4() returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] credit_debit.creditDebitTestNGSlow.dataProviderMethod4() returned a null value
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testMethod4 -->
  <testcase name="testMethod2" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <failure type="org.testng.TestNGException" message="
Data Provider public synchronized java.lang.Object[][] credit_debit.creditDebitTestNGSlow.dataProviderMethod2() returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] credit_debit.creditDebitTestNGSlow.dataProviderMethod2() returned a null value
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod3" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <failure type="org.testng.TestNGException" message="
Data Provider public synchronized java.lang.Object[][] credit_debit.creditDebitTestNGSlow.dataProviderMethod3() returned a null value">
      <![CDATA[org.testng.TestNGException: 
Data Provider public synchronized java.lang.Object[][] credit_debit.creditDebitTestNGSlow.dataProviderMethod3() returned a null value
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body

at credit_debit.creditDebitTestNGSlow.testMethod1(creditDebitTestNGSlow.java:585)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body

at credit_debit.creditDebitTestNGSlow.testMethod1(creditDebitTestNGSlow.java:585)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.001" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body

at credit_debit.creditDebitTestNGSlow.testMethod1(creditDebitTestNGSlow.java:585)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.001" classname="credit_debit.creditDebitTestNGSlow">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body

at credit_debit.creditDebitTestNGSlow.testMethod1(creditDebitTestNGSlow.java:585)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <skipped/>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="0.0" classname="credit_debit.creditDebitTestNGSlow">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body

at credit_debit.creditDebitTestNGSlow.testMethod1(creditDebitTestNGSlow.java:585)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
</testsuite> <!-- Rebill Test -->
